### ISSUE TITLE
Libraries to implement in 1.4

### ISSUE THREAD

**Issue by mytja** [mytja/MyAssistantOS-Raspbian#59]
I'll implement next libraries:
- [ ] OpenStreetMap (no API) - see issue #58 - https://pypi.org/project/openstreetmap/
- [ ] Wolfram Alpha (requires API) - see issue #55 - https://pypi.org/project/wolframalpha/ or https://pypi.org/project/wolframalpha-asyncio/
- [ ] NewsAPI wrapper (requires API) - see issue #56 - https://github.com/mytja/NewsAPI-Python
Thanks to @alexmercerind for submitting NewsAPI. Without him this library won't exist
- [ ] Replace OS with more efficent subprocess
